<a href="https://colab.research.google.com/github/theweird-kid/ML-Notes/blob/main/Maths/Matrix_Ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Creating Matrices

In [ ]:
import numpy as np

mat_a = np.array([[2, 4], [3, 2]])
mat_a.shape

(2, 2)

In [ ]:
print(mat_a)

[[2 4]
 [3 2]]


In [ ]:
mat_b = np.array([[11, 12, 3], [4, 6, 7], [19, 12, 13]])

In [ ]:
mat_b.shape

(3, 3)

Generating Matrices with Random Values

In [ ]:
mat_rando = np.random.rand(3, 3)

In [ ]:
print(mat_rando)

[[0.87186234 0.0148397  0.13494662]
 [0.57515367 0.74525111 0.93571903]
 [0.10073786 0.84063422 0.55494133]]


Random Matrix with Integer Values

In [ ]:
# Matrix with random Integers less than 100
mat_rando = np.random.randint(100, size=(3, 3))

In [ ]:
print(mat_rando)

[[29 95 26]
 [45  1 77]
 [75 79  1]]


Matrix with All values as 1s

In [ ]:
# By Default everything is floating point, mention dtype to get int or something
mat_1s = np.ones((7, 3), dtype=int)

In [ ]:
print(mat_1s)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
# Null or Zero Matrix
mat_0 = np.zeros((5, 5), dtype=int)
print(mat_0)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [ ]:
# Identity Matrix
mat_ident = np.eye(6, dtype=int)
print(mat_ident)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


Matrix Operations

In [ ]:
# Transpose of a matrix
mat_ = np.random.randint(100, size=(4, 5))
print(mat_)

[[69 37  8 23 34]
 [71 27 43 27 55]
 [25 85 81 49 73]
 [ 9 24 62 10 27]]


In [ ]:
# Print Transpose
mat_trans_ = mat_.transpose()
print(mat_trans_)

[[69 71 25  9]
 [37 27 85 24]
 [ 8 43 81 62]
 [23 27 49 10]
 [34 55 73 27]]


In [ ]:
# Matrix Multiplication -> Note: Use np.dot(mat_a_, mat_b_) instead of np.multiply for "MATRIX MULTIPLICATION".
# the .multiply is for elementwise Multiplication
mat_a = np.random.randint(15, size=(3, 3))
mat_b = np.random.randint(20, size=(3, 3))

print(mat_a)
print(mat_b)

mat_dot = np.dot(mat_a, mat_b)
print(mat_dot)

[[ 3  7  2]
 [10 12 12]
 [ 0 13  6]]
[[18 15  6]
 [ 5  6 15]
 [15  8  7]]
[[119 103 137]
 [420 318 324]
 [155 126 237]]
