<a href="https://colab.research.google.com/github/theweird-kid/ML-Notes/blob/main/Basics/NumpyBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
from time import process_time

In [ ]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time-start_time)

0.0005354290000001427


In [ ]:
np_array = np.array([1, 2, 4, 5, 6])
type(np_array)

numpy.ndarray

In [ ]:
# 2D array
b = np.array([(1, 2, 3, 4, 5), (6, 1, 2, 8, 11)])
print(b)
b.shape

[[ 1  2  3  4  5]
 [ 6  1  2  8 11]]


(2, 5)

In [ ]:
c = np.array([(1, 2, 4, 5), (11, 12.3, 14, 11)], dtype=float)
print(c)

[[ 1.   2.   4.   5. ]
 [11.  12.3 14.  11. ]]


In [ ]:
# Initial Place Holders

# Numpy array of zeros

x = np.zeros((4, 5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
y = np.ones((3, 3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# Array of a particular value
arr = np.full((4, 5), 11)
print(arr)

[[11 11 11 11 11]
 [11 11 11 11 11]
 [11 11 11 11 11]
 [11 11 11 11 11]]


In [ ]:
# create an identity matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# create a numpy arr with rand values
b = np.random.random((3, 4))
print(b)

[[0.95842826 0.76924056 0.27936005 0.53263287]
 [0.88993235 0.80370291 0.97101814 0.00118899]
 [0.66759268 0.51583758 0.936599   0.67919861]]


In [ ]:
# rand int value array within range
c = np.random.randint(10,100, (3, 5))
print(c)

[[74 22 78 35 63]
 [97 51 38 84 63]
 [92 61 35 25 99]]


In [ ]:
# array of evenly spaced vals --> by specifying num of values req
d = np.linspace(10, 30, 6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [ ]:
# array of evenly spaced vals --> specifying the step

e = np.arange(10, 30, 5)
print(e)

[10 15 20 25]


In [ ]:
# convert a list to a np array

list2 = [10, 20, 30, 16, 78]

np_array = np.asarray(list2)
print(type(list2))
print(type(np_array))

print(np_array)

<class 'list'>
<class 'numpy.ndarray'>
[10 20 30 16 78]


In [ ]:
# Analyzing an np array

c = np.random.randint(10, 90, (6, 6))
print(c)

[[73 13 39 61 11 12]
 [71 37 54 76 75 53]
 [50 41 30 56 41 25]
 [57 58 49 73 10 67]
 [80 58 12 19 52 79]
 [46 43 11 54 53 80]]


In [ ]:
# find array dim
c.shape

(6, 6)

In [ ]:
# number of dims
print(c.ndim)

2


In [ ]:
# number of elems in array
print(c.size)

36


In [ ]:
# checking data type of values in array

print(c.dtype)

int64


In [ ]:
# Maths on np array
a = np.random.randint(10, 30, (4, 4))
b = np.random.randint(11, 100, (4, 4))


In [ ]:
print(a)
print(b)

[[28 28 29 14]
 [23 25 19 21]
 [17 16 20 13]
 [11 18 29 18]]
[[63 27 39 31]
 [85 43 45 28]
 [50 13 33 35]
 [81 93 78 22]]


In [ ]:
# Element wise operations
c = np.add(a, b)
print(c)

[[ 91  55  68  45]
 [108  68  64  49]
 [ 67  29  53  48]
 [ 92 111 107  40]]


In [ ]:
print(np.divide(a, b))

[[0.44444444 1.03703704 0.74358974 0.4516129 ]
 [0.27058824 0.58139535 0.42222222 0.75      ]
 [0.34       1.23076923 0.60606061 0.37142857]
 [0.13580247 0.19354839 0.37179487 0.81818182]]


In [ ]:
print(np.subtract(a, b))

[[-35   1 -10 -17]
 [-62 -18 -26  -7]
 [-33   3 -13 -22]
 [-70 -75 -49  -4]]


In [ ]:
print(np.multiply(a, b))

[[1764  756 1131  434]
 [1955 1075  855  588]
 [ 850  208  660  455]
 [ 891 1674 2262  396]]


In [ ]:
# Array Manipulation

arr = np.random.randint(0, 10, (2, 3))
print(arr)
print(arr.shape)


[[3 2 3]
 [3 8 3]]
(2, 3)


In [ ]:
arr_trans = np.transpose(arr)
print(arr_trans)
print(arr_trans.shape)

[[3 3]
 [2 8]
 [3 3]]
(3, 2)


In [ ]:
# reshape an array
a = np.random.randint(0, 10, (2, 3))
print(a)
print(a.shape)

[[4 7 3]
 [4 0 6]]
(2, 3)


In [ ]:
b = a.reshape(3, 2)

In [ ]:
print(b)

[[4 7]
 [3 4]
 [0 6]]


In [ ]:
print(b.shape)

(3, 2)
